name: ci
on:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ditsuke/dpaste-cli/.github/workflows/checkout-and-setup-go.yml@ci/actions

      - name: golang-ci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

#  build:
#    strategy:
#      fail-fast: true
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup go
#        uses: actions/setup-go
